name: Host Info Server Build Automation

on:
  push:
    paths:
      - python/**
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11','3.12']
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    
    - name: Verify code builds
      run: |
        python -m py_compile python/host_info_server.py
        ls -lR python/
    
    - name: Run unit tests
      run: |
        cd python/
        python -m unittest test_hostinfo.py
    
    - name: Generate coverage report
      run: |
        cd python/
        coverage run -m unittest test_hostinfo.py
        coverage report -m
      
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [flake8, pylint, ruff, mypy, pytype, pyright, fixit, pyre]    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: |
        cd python/
    - uses: advanced-security/python-lint-code-scanning-action@v1
      with:
        linter: ${{ matrix.linter }}
